name: Publish Docs Trigger
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

env:
  # Repository where the cloud tests will be run
  REPOSITORY: ${{ github.repository_owner }}/wise-agents.github.io
  # This must be set to a PAT with 'repo' permission for the target repository
  TOKEN: ${{ secrets.PUBLISH_DOCS_REMOTE_DISPATCH_TOKEN }}
  # Just an identifier for the event - this one triggers the cloud tests
  EVENT_TYPE: publish-docs

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Remote Dispatch
        if: ${{ env.TOKEN }}
        run: |
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          PR_NUMBER="${{github.event.number}}"

          CLIENT_PAYLOAD=$( jq -n \
                  --arg githubSha "$GITHUB_SHA" \
                  '{githubSha: $githubSha}' )

          echo "CLIENT_PAYLOAD: $CLIENT_PAYLOAD"

          set -x

          resp=$(curl -X POST -s "https://api.github.com/repos/${REPOSITORY}/dispatches" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${TOKEN}" \
              -d "{\"event_type\": \"${EVENT_TYPE}\", \"client_payload\": ${CLIENT_PAYLOAD} }")

          set +x

          if [ -z "$resp" ]
          then
            sleep 2
          else
            echo "Workflow failed to trigger"
            echo "$resp"
            exit 1
          fi